name:                PokerNN
version:             1.0.0
github:              "regzand/PokerNN"
license:             BSD3
author:              "Jan Gołda & Mateusz Szpyrka"
maintainer:          "jan.golda@gmail.com"
copyright:           "2018 Jan Gołda & Mateusz Szpyrka"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/regzand/PokerNN#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- normaldistribution
- random-shuffle
- parallel

library:
  source-dirs: src

executables:
  PokerNN-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PokerNN

tests:
  PokerNN-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PokerNN
    - HUnit
    - QuickCheck
